
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mosef
 */
public class SnowflakeFrame extends javax.swing.JFrame {

    private boolean darkmodeEnabled = false;
    private int oldWidth = 0;
    private int oldHeight = 0;
    /**
     * Creates new form SnowflakeFrame
     */
    public SnowflakeFrame() {
        initComponents();
        snowflakePanel1.setVisible(true);
        generaLiveButton.setBackground(Color.WHITE);
        generaLiveButton.setForeground(Color.BLACK);
        savePointsButton.setBackground(Color.WHITE);
        savePointsButton.setForeground(Color.BLACK);
        leftPanel.setBackground(Color.WHITE);
        darkmodeCheckBox.setForeground(Color.BLACK);
        darkmodeCheckBox.setBackground(Color.WHITE);
        deletePointsButton.setForeground(Color.BLACK);
        deletePointsButton.setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox2 = new javax.swing.JCheckBox();
        leftPanel = new javax.swing.JPanel();
        generaLiveButton = new javax.swing.JButton();
        savePointsButton = new javax.swing.JButton();
        deletePointsButton = new javax.swing.JButton();
        darkmodeCheckBox = new javax.swing.JCheckBox();
        snowflakePanel1 = new SnowflakePanel();

        jCheckBox2.setText("jCheckBox2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(640, 500));
        setName("SnowflakeFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(500, 650));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        leftPanel.setLayout(new java.awt.GridLayout(4, 1));

        generaLiveButton.setText("Genera live");
        generaLiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generaLiveButtonActionPerformed(evt);
            }
        });
        leftPanel.add(generaLiveButton);

        savePointsButton.setText("Save Points");
        leftPanel.add(savePointsButton);

        deletePointsButton.setText("Delete points");
        deletePointsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePointsButtonActionPerformed(evt);
            }
        });
        leftPanel.add(deletePointsButton);

        darkmodeCheckBox.setText("Darkmode");
        darkmodeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkmodeCheckBoxActionPerformed(evt);
            }
        });
        leftPanel.add(darkmodeCheckBox);

        getContentPane().add(leftPanel, java.awt.BorderLayout.LINE_START);

        snowflakePanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(snowflakePanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generaLiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generaLiveButtonActionPerformed
        snowflakePanel1.switchLive();
    }//GEN-LAST:event_generaLiveButtonActionPerformed

    private void darkmodeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkmodeCheckBoxActionPerformed
        darkmodeEnabled = !darkmodeEnabled;
        switchDarkmode();
        snowflakePanel1.switchDarkmode();
    }//GEN-LAST:event_darkmodeCheckBoxActionPerformed

    private void deletePointsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePointsButtonActionPerformed
        snowflakePanel1.deletePoints();
    }//GEN-LAST:event_deletePointsButtonActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
 
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SnowflakeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SnowflakeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SnowflakeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SnowflakeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SnowflakeFrame().setVisible(true);
            }
        });
    }
    
    public void switchDarkmode() {
        if(darkmodeEnabled) {
             generaLiveButton.setBackground(Color.BLACK);
             generaLiveButton.setForeground(Color.WHITE);
             savePointsButton.setBackground(Color.BLACK);
             savePointsButton.setForeground(Color.WHITE);
             leftPanel.setBackground(Color.DARK_GRAY);       
             darkmodeCheckBox.setForeground(Color.WHITE);
             darkmodeCheckBox.setBackground(Color.BLACK); 
             deletePointsButton.setForeground(Color.WHITE);
             deletePointsButton.setBackground(Color.BLACK);
        }else{
             generaLiveButton.setBackground(Color.WHITE);
             generaLiveButton.setForeground(Color.BLACK);
             savePointsButton.setBackground(Color.WHITE);
             savePointsButton.setForeground(Color.BLACK);
             leftPanel.setBackground(Color.WHITE);   
             darkmodeCheckBox.setForeground(Color.BLACK);
             darkmodeCheckBox.setBackground(Color.WHITE); 
             deletePointsButton.setForeground(Color.BLACK);
             deletePointsButton.setBackground(Color.WHITE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox darkmodeCheckBox;
    private javax.swing.JButton deletePointsButton;
    private javax.swing.JButton generaLiveButton;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton savePointsButton;
    private SnowflakePanel snowflakePanel1;
    // End of variables declaration//GEN-END:variables
}
