
import java.awt.Color;
import java.io.IOException;
import java.nio.file.Path;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author Mosè Ferrazzini
 * @version 20.12.2019
 */
public class StartFrame extends javax.swing.JFrame {

    /**
     * Creates new form StartFrame
     */
    public StartFrame() {
        ImageIcon imgicon = new ImageIcon("../flakeIcon.ico");
        this.setIconImage(imgicon.getImage());
        initComponents();
        this.setTitle("Snowflake Menu");
        topPanel.setBackground(Color.WHITE);
        bottomLeftPanel.setBackground(Color.WHITE);
        bottomRightPanel.setBackground(Color.WHITE);
        newSnowflakeButton.setBackground(Color.WHITE);
        openSnowflakeButton.setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        bottomLeftPanel = new javax.swing.JPanel();
        newSnowflakeButton = new javax.swing.JButton();
        bottomRightPanel = new javax.swing.JPanel();
        openSnowflakeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 450));
        setSize(new java.awt.Dimension(600, 450));
        getContentPane().setLayout(new java.awt.GridLayout(2, 2, 2, 0));

        topPanel.setLayout(new java.awt.GridLayout(1, 1));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Snowflake Generator");
        topPanel.add(titleLabel);

        getContentPane().add(topPanel);

        bottomPanel.setLayout(new java.awt.GridLayout(1, 0));

        bottomLeftPanel.setLayout(new java.awt.GridBagLayout());

        newSnowflakeButton.setText("New Snowflake");
        newSnowflakeButton.setMinimumSize(new java.awt.Dimension(75, 23));
        newSnowflakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSnowflakeButtonActionPerformed(evt);
            }
        });
        bottomLeftPanel.add(newSnowflakeButton, new java.awt.GridBagConstraints());

        bottomPanel.add(bottomLeftPanel);

        bottomRightPanel.setLayout(new java.awt.GridBagLayout());

        openSnowflakeButton.setText("Open Snowflake");
        openSnowflakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openSnowflakeButtonActionPerformed(evt);
            }
        });
        bottomRightPanel.add(openSnowflakeButton, new java.awt.GridBagConstraints());

        bottomPanel.add(bottomRightPanel);

        getContentPane().add(bottomPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newSnowflakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSnowflakeButtonActionPerformed
        SnowflakeFrame sf = new SnowflakeFrame();
        sf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_newSnowflakeButtonActionPerformed

    private void openSnowflakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openSnowflakeButtonActionPerformed
        SnowflakeFrame sf = new SnowflakeFrame();
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("snowflake files (*.flake)", "flake");
        chooser.addChoosableFileFilter(filter);
        chooser.setFileFilter(filter);
        chooser.setDialogTitle("Import points");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            Path origine = chooser.getSelectedFile().toPath();
            try {
                Saver s = new Saver(origine);
                sf.snowflakePanel1.setTrianglePoints(s.getTrianglePoints());
                sf.snowflakePanel1.setCutPoints(s.getCutPoints());
                sf.setVisible(true);
                this.dispose();
            }catch (IOException ioe) {
                showMessageDialog(null, "Impossibile leggere il file.");
            }
        } 
    }//GEN-LAST:event_openSnowflakeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomLeftPanel;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel bottomRightPanel;
    private javax.swing.JButton newSnowflakeButton;
    private javax.swing.JButton openSnowflakeButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
